spark.eventLog.enabled                 true
spark.eventLog.dir                     file:/opt/sparkos/artifacts/spark-events
spark.history.fs.logDirectory          file:/opt/sparkos/artifacts/spark-events
spark.sql.session.timeZone             Asia/Shanghai
spark.sql.shuffle.partitions           4
spark.ui.showConsoleProgress            false
