api:
  base_url: "http://localhost:20128/v1"
  api_key: "sk-54027ea1b7cab6a1-9yi909-90d259c0"
  model: "yuanshennb"
Embedding_api:
  model: "wo/text-embedding-3-large"
  base_url: "http://localhost:20128"
  api_key: "sk-54027ea1b7cab6a1-9yi909-90d259c0"
spark:
  container: "sparkos-spark-master"
  spark_bin: "/opt/spark/bin/spark-submit"
  master_url: "spark://spark-master:7077"
  default_executor_memory: "2g"
  default_executor_cores: 2
  default_num_executors: 2
  default_driver_memory: "2g"